### ISSUE TITLE
內嵌 hackmd.io

### ISSUE THREAD

**Issue by ETBlue** [ETBlue/debater#11]
lalala

**Comment by jackycute** [comment]
請問可以詳細描述一下這個 issue 嗎？

**Comment by ddio** [comment]
印象中是可以直接在 debater 裡直接放 hackmd.io 的畫面，這樣就可以在同一個畫面裡編輯 + 更新 debater

**Comment by jackycute** [comment]
喔喔，不錯的 idea

**Comment by ETBlue** [comment]
對啊，不能在同個畫面編輯真的超煩的 XD 當初 hackfoldr 1.0 也是得另開分頁才能編輯 spreadsheet，然後切分頁，refresh，再切分頁，再編輯，再切分頁，再 refresh...（倒

**Comment by MrOrz** [comment]
講個秘訣

https://support.apple.com/zh-tw/HT204948

（逃
