### ISSUE TITLE
來自 mobile 的悲劇 XD

### ISSUE THREAD

**Issue by ETBlue** [ETBlue/debater#6]
![fireshot capture 176 - flyingv i debater_ online opinions _ - http___etblue github io_debater_](https://cloud.githubusercontent.com/assets/244354/12930571/fd42b040-cfb3-11e5-89bf-e5ba2c54b26f.png)

**Comment by jackycute** [comment]
啊，隨風去吧，好啦修一下

**Comment by jackycute** [comment]
這應該在 302fa9521a82c5385c494aeb9deb4a31fdd0bab5 修正了
