### ISSUE TITLE
同場加映：來自 27 吋大螢幕的悲劇 XD

### ISSUE THREAD

**Issue by ETBlue** [ETBlue/debater#7]
![fireshot capture 177 - flyingv i debater_ online opinions _ - http___etblue github io_debater_](https://cloud.githubusercontent.com/assets/244354/12930627/57712984-cfb4-11e5-988a-11102b8bd20a.png)

**Comment by jackycute** [comment]
我要崩潰了啊，好啦晚點修一下

**Comment by ETBlue** [comment]
先睡吧，對八卦工具不要太認真啦 XD 我也要先撤退了，為了追這八卦今天的電動都還沒打... zzz

**Comment by jackycute** [comment]
別擔心我這裡才下午3點多 XDD（偏執狂發作

**Comment by jackycute** [comment]
這應該在 d235bb2f387db1e5cf5715f04891efd567c1f5d8 修正了
