### ISSUE TITLE
summary 需求

### ISSUE THREAD

**Issue by ETBlue** [ETBlue/debater#9]
懶人包小編撰寫摘要的地方，需可分段
suggested by @slc-git

**Comment by ETBlue** [comment]
每個tag可以跟著一個summary欄位，一直fixed top，可expand 或collapse

**Comment by ETBlue** [comment]
basically done by e62d6245d9ca5a01c21dc86c2fc86506337dcd17
still need some polish, though

**Comment by slc-git** [comment]
hurrray!!! thank you!!!
